import type { Metadata } from "next";
import { Providers } from "../providers";
import "../../styels/globals.css";
import Sidebar from "@/components/sidebar/Sidebar";
import Navbar from "@/components/navbar/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased">
        <Providers>
          <div className="flex flex-col min-h-screen">
            <Navbar />

            <main className="flex flex-grow">
              {/* Sidebar */}
              <Sidebar />
              {/* Main Content */}
              <div className="flex-grow p-6 ml-0  transition-all ">
                {children}
              </div>
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
